channels:
- conda-forge
dependencies:
- python=3.11.13
- pip<=25.3
- pip:
  - mlflow==3.4.0
  - cloudpickle==3.1.1
  - numpy==2.3.4
  - pandas==2.3.3
  - psutil==6.0.0
  - pyarrow==21.0.0
  - scikit-learn==1.7.2
  - scipy==1.16.3
name: mlflow-env
